/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryNameIdIndexRouteImport } from './routes/$categoryNameId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryNameIdIndexRoute = CategoryNameIdIndexRouteImport.update({
  id: '/$categoryNameId/',
  path: '/$categoryNameId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$categoryNameId': typeof CategoryNameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$categoryNameId': typeof CategoryNameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$categoryNameId/': typeof CategoryNameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$categoryNameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$categoryNameId'
  id: '__root__' | '/' | '/$categoryNameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryNameIdIndexRoute: typeof CategoryNameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categoryNameId/': {
      id: '/$categoryNameId/'
      path: '/$categoryNameId'
      fullPath: '/$categoryNameId'
      preLoaderRoute: typeof CategoryNameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryNameIdIndexRoute: CategoryNameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
