"""soft delete timestamp

Revision ID: 666f466f4957
Revises: dd4c6b9c5f04
Create Date: 2025-09-05 00:29:55.865438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666f466f4957'
down_revision: Union[str, Sequence[str], None] = 'dd4c6b9c5f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('item', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('itemtype', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemtype', 'deleted_at')
    op.drop_column('item', 'deleted_at')
    op.drop_column('category', 'deleted_at')
    # ### end Alembic commands ###
