// This file is auto-generated by @hey-api/openapi-ts

/**
 * GetCategoriesResponse
 */
export type GetCategoriesResponse = {
    /**
     * Data
     */
    data: Array<PublicCategory>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NewCategoryBody
 */
export type NewCategoryBody = {
    /**
     * Category Name
     */
    category_name: string;
};

/**
 * NewCategoryResponse
 */
export type NewCategoryResponse = {
    data: PublicCategory;
};

/**
 * PublicCategory
 */
export type PublicCategory = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name Id
     */
    name_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Items
     */
    items: Array<PublicCategoryItem>;
};

/**
 * PublicCategoryItem
 */
export type PublicCategoryItem = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
    item_type: PublicCategoryItemType;
};

/**
 * PublicCategoryItemType
 */
export type PublicCategoryItemType = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include[Items]
         */
        'include[items]'?: boolean;
        /**
         * Filter[Name Id]
         */
        'filter[name_id]'?: string | null;
    };
    url: '/categories/';
};

export type GetCategoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCategoriesError = GetCategoriesErrors[keyof GetCategoriesErrors];

export type GetCategoriesResponses = {
    /**
     * Successful Response
     */
    200: GetCategoriesResponse;
};

export type GetCategoriesResponse2 = GetCategoriesResponses[keyof GetCategoriesResponses];

export type NewCategoryData = {
    body: NewCategoryBody;
    path?: never;
    query?: never;
    url: '/categories/';
};

export type NewCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewCategoryError = NewCategoryErrors[keyof NewCategoryErrors];

export type NewCategoryResponses = {
    /**
     * Successful Response
     */
    200: NewCategoryResponse;
};

export type NewCategoryResponse2 = NewCategoryResponses[keyof NewCategoryResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};