// This file is auto-generated by @hey-api/openapi-ts

/**
 * GetCategoriesResponse
 */
export type GetCategoriesResponse = {
    /**
     * Data
     */
    data: Array<PublicCategory>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PublicCategory
 */
export type PublicCategory = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name Id
     */
    name_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Item Types
     */
    item_types: Array<PublicItemType>;
    /**
     * Items
     */
    items: Array<PublicItem>;
};

/**
 * PublicItem
 */
export type PublicItem = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * PublicItemType
 */
export type PublicItemType = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include[Item Types]
         */
        'include[item_types]'?: boolean;
        /**
         * Include[Items]
         */
        'include[items]'?: boolean;
        /**
         * Filter[Name Id]
         */
        'filter[name_id]'?: string | null;
    };
    url: '/categories/';
};

export type GetCategoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCategoriesError = GetCategoriesErrors[keyof GetCategoriesErrors];

export type GetCategoriesResponses = {
    /**
     * Successful Response
     */
    200: GetCategoriesResponse;
};

export type GetCategoriesResponse2 = GetCategoriesResponses[keyof GetCategoriesResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};