// This file is auto-generated by @hey-api/openapi-ts

/**
 * ExistingCategoryErrorResponse
 */
export type ExistingCategoryErrorResponse = {
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Message
     */
    message?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NonExistentCategoryErrorResponse
 */
export type NonExistentCategoryErrorResponse = {
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Message
     */
    message?: string;
};

/**
 * NotCreatedCategoryErrorResponse
 */
export type NotCreatedCategoryErrorResponse = {
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Message
     */
    message?: string;
};

/**
 * NotCreatedItemsErrorResponse
 */
export type NotCreatedItemsErrorResponse = {
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Message
     */
    message?: string;
};

/**
 * NotUpdatedCategoryErrorResponse
 */
export type NotUpdatedCategoryErrorResponse = {
    /**
     * Status Code
     */
    status_code?: number;
    /**
     * Message
     */
    message?: string;
};

/**
 * PublicCategory
 */
export type PublicCategory = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name Id
     */
    name_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Items
     */
    items: Array<PublicCategoryItem>;
};

/**
 * PublicCategoryItem
 */
export type PublicCategoryItem = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
    item_type: PublicCategoryItemType;
};

/**
 * PublicCategoryItemType
 */
export type PublicCategoryItemType = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * RequestBody
 */
export type AppRoutesCategoriesEditCategoryRequestBody = {
    /**
     * Category Name
     */
    category_name?: string | null;
};

/**
 * ResponseBody
 */
export type AppRoutesCategoriesEditCategoryResponseBody = {
    data: PublicCategory;
};

/**
 * ResponseBody
 */
export type AppRoutesCategoriesGetCategoriesResponseBody = {
    /**
     * Data
     */
    data: Array<PublicCategory>;
};

/**
 * RequestBody
 */
export type AppRoutesCategoriesNewCategoryRequestBody = {
    /**
     * Category Name
     */
    category_name: string;
};

/**
 * ResponseBody
 */
export type AppRoutesCategoriesNewCategoryResponseBody = {
    data: PublicCategory;
};

/**
 * RequestBody
 */
export type AppRoutesItemTypesNewItemTypeRequestBody = {
    /**
     * Item Type Name
     */
    item_type_name: string;
    /**
     * Item Ct
     */
    item_ct: number;
    /**
     * Category Name Id
     */
    category_name_id: string;
};

/**
 * ResponseBody
 */
export type AppRoutesItemTypesNewItemTypeResponseBody = {
    /**
     * Success
     */
    success?: boolean;
};

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include[Items]
         */
        'include[items]'?: boolean;
        /**
         * Filter[Name Id]
         */
        'filter[name_id]'?: string | null;
    };
    url: '/categories/';
};

export type GetCategoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCategoriesError = GetCategoriesErrors[keyof GetCategoriesErrors];

export type GetCategoriesResponses = {
    /**
     * Successful Response
     */
    200: AppRoutesCategoriesGetCategoriesResponseBody;
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type NewCategoryData = {
    body: AppRoutesCategoriesNewCategoryRequestBody;
    path?: never;
    query?: never;
    url: '/categories/';
};

export type NewCategoryErrors = {
    /**
     * Existing Category
     */
    409: ExistingCategoryErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Not Created Category
     */
    502: NotCreatedCategoryErrorResponse;
};

export type NewCategoryError = NewCategoryErrors[keyof NewCategoryErrors];

export type NewCategoryResponses = {
    /**
     * Successful Response
     */
    200: AppRoutesCategoriesNewCategoryResponseBody;
};

export type NewCategoryResponse = NewCategoryResponses[keyof NewCategoryResponses];

export type RemoveCategoryData = {
    body?: never;
    headers: {
        /**
         * Authorization
         */
        authorization: string;
    };
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/categories/{uuid}';
};

export type RemoveCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveCategoryError = RemoveCategoryErrors[keyof RemoveCategoryErrors];

export type RemoveCategoryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EditCategoryData = {
    body: AppRoutesCategoriesEditCategoryRequestBody;
    headers: {
        /**
         * Authorization
         */
        authorization: string;
    };
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/categories/{uuid}';
};

export type EditCategoryErrors = {
    /**
     * Non-Existent Category
     */
    404: NonExistentCategoryErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Not Updated Category
     */
    502: NotUpdatedCategoryErrorResponse;
};

export type EditCategoryError = EditCategoryErrors[keyof EditCategoryErrors];

export type EditCategoryResponses = {
    /**
     * Successful Response
     */
    200: AppRoutesCategoriesEditCategoryResponseBody;
};

export type EditCategoryResponse = EditCategoryResponses[keyof EditCategoryResponses];

export type NewItemTypeData = {
    body: AppRoutesItemTypesNewItemTypeRequestBody;
    path?: never;
    query?: never;
    url: '/item_types/';
};

export type NewItemTypeErrors = {
    /**
     * Non-Existent Category
     */
    404: NonExistentCategoryErrorResponse;
    /**
     * Not Created Items
     */
    409: NotCreatedItemsErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewItemTypeError = NewItemTypeErrors[keyof NewItemTypeErrors];

export type NewItemTypeResponses = {
    /**
     * Successful Response
     */
    200: AppRoutesItemTypesNewItemTypeResponseBody;
};

export type NewItemTypeResponse = NewItemTypeResponses[keyof NewItemTypeResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};